config/routes.rb
Rails.application.routes.draw do


  root 'pages#home'
  # get 'users/show'

  get '/filter', to: 'pages#filter'

  devise_for :users, :path => 'accounts'

  resources :users, only: [:show] do
    resources :stallions do
      resources :bookings, only: [:new, :create]
    end

    # resources :profiles, only: [:new, :create, :edit, :update]
  end

  get 'users/:id/profile' => 'profiles#show', as: :user_profile
  get 'users/:id/profile/new' => 'profiles#new', as: :new_user_profile
  post 'users/profiles' => 'profiles#create'
  get 'users/:id/profile/edit' => 'profiles#edit', as: :edit_user_profile
  patch 'users/:id/profile' => 'profiles#update'

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/stallion.rb
class Stallion < ActiveRecord::Base
  belongs_to :user
  has_many :availabilities
  has_many :bookings
  # validates :user_id, presence: true
  # has_many :users, through: :bookings

  mount_uploader :photo, PhotoUploader

  CATEGORIES = ["Rodeo", "Jumping", "Racing", "Working"]
  BREEDS = ["Belgian Warmblood", "Clydesdale", "Shire Horse",
      "Shetland Pony", "Arabian", "Quarterhorse", "Thoroughbred", "Pecheron", "Apaloosa",
      "American Paint", "Fjord Horse", "Nokota", "Chilean"]
  # COLOUR = ["black", "brown", "white", "grey", "white"]
  # COUNTRY = ["Belgium","France","The Netherlands", "United Arab Emirates", ]
  SERVICES = ["sperm_only", "stabling", "owner_bed", "shooting", "malt_whisky"]


def self.ratings
  interim = Stallion.all
  ratingslist = interim.map do |f|
    f.average_rating
  end
  ratingslist.uniq
end

def self.countries
  interim = Stallion.all
  contrieslist = interim.map do |f|
    f.country
  end
  contrieslist.uniq
end

def self.breeds
interim = Stallion.all
  breedslist = interim.map do |f|
    f.breed
  end
  breedslist.uniq
end

def self.categories
interim = Stallion.all
  categorieslist = interim.map do |f|
    f.category
  end
  categorieslist.uniq
end

end

app/controllers/stallions_controller.rb
class StallionsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_user, only: [:create, :new, :edit, :update]

  def index
    @stallions = Stallion.all
  end

  def show
    @stallion = Stallion.find(params[:id])
  end


  def new
    @stallion = Stallion.new
    @form_variables = {header: "Add"}
  end


  def create
    @stallion = @user.stallions.build(stallion_params)
    if @stallion.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def edit
    set_stallion
    @form_variables = {header: "Edit"}
  end


  def update
    set_stallion
    find_user
    @stallion.update(stallion_params)
    redirect_to user_stallion_path(@user.id, @stallion.id)
  end

  def destroy
    @stallion = Stallion.find(params[:id])
    @stallion.destroy()
    redirect_to user_path
  end

  private

  def set_stallion
    @stallion = Stallion.find(params[:id])
  end

  # image is from seed, photo is from cloudinary
  def stallion_params
    params.require(:stallion).permit(
      :image,
      :name,
      :date_of_birth,
      :category,
      :breed,
      :town,
      :country,
      :lineage,
      :description,
      :colour,
      :sperm_only,
      :stabling,
      :malt_whisky,
      :shooting,
      :owner_bed,
      :photo,
      :photo_cache)
  end

  def find_user
   @user = User.find(current_user.id)
   @user.stallion_owner = true
 end
end

app/helpers/stallions_helper.rb
module StallionsHelper
end

app/views/stallions/destroy.html.erb
<h1>Stallions#destroy</h1>
<p>Find me in app/views/stallions/destroy.html.erb</p>

app/views/stallions/edit.html.erb
<%= render 'shared/form_add_edit_stallion' %>

app/views/stallions/index.html.erb
<!--This needs to be changed to CSS and classes at some point -->
<center><h1>MareBNB<h1>
<p>Your Horse Will Thank You<p></center>
<br>
<br>
<br>
<br>



<div class="container">
  <div class="row">
    <% Stallion.all.each do |stallion| %>
    <div class="col-xs-12 col-sm-3">
  <%=  link_to user_stallion_path(stallion.user, stallion) do %>
      <div class="card" style="background-image: url('<%= image_url stallion.photo %>'), linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">

        <div class="card-category"><%= stallion.town %></div>
        <div class="card-description">
          <h2><%= stallion.name %></h2>
          <p><%= stallion.category %>  -  <%= stallion.breed %></p>
        </div>
<!--         <a href="#" class="card-link"></a> -->
      </div>

      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/stallions/new.html.erb
<% if @user.stallion_owner %>

<%= render 'shared/form_add_edit_stallion' %>

<% else %>

<p>You're not registered as a stallion owner. Please check your profile.</p>

<% end %>

app/views/stallions/show.html.erb
<% content_for(:title) do %>
  <%= @stallion.name %> is available on Mare BnB!
<% end %>

<div id="banner-show-stallion" style="background-image: url('<%= image_url @stallion.photo %>');">
</div>



<!-- stallion summary and booking form-->
<div class="wrapper-white">
  <div class="container">
    <div class="row">

      <div class="col-xs-12 col-sm-5 col-sm-offset-1">
        <div class="summary">
          <div class="summary-owner">
            <!-- TODO: Change profile pic to variable -->
            <%= image_tag "#{@stallion.user.profile.photo}", class:"avatar-large" %>
            <div>
              <%= @stallion.user.profile.title %> <%= @stallion.user.profile.last_name %>
            </div>
          </div>


          <div class="summary-stallion">
            <!--         this is a flex item on the right -->
            <h4><%= @stallion.name %></h4>
            <p><%= @stallion.town.capitalize %>, <%= @stallion.country.capitalize %></p>
            <p>
              <% if @stallion.average_rating.nil? %>
              <% 10.times do %>
              <i class="fa fa-star star-grey"></i>
              <% end %>
              <% else %>
              <% @stallion.average_rating.times do %>
              <i class="fa fa-star star-gold"></i>
              <% end %>

              <% (10 - @stallion.average_rating).times do %>
              <i class="fa fa-star star-grey"></i>
              <% end %>
              <% end %>
            </p>
          </div>
        </div>
      </div>


      <div class="col-xs-12 col-sm-4 col-sm-offset-1">
        <div class="booking-form-box-grey">
          <form id="stallion-booking-form">
<!--             <div class="row">
              <div class="form_group">
                <h4>Book this stallion</h4>
              </div>
              <div class="col-xs-12 col-sm-6">
                <div class="form-group">
                  <input type="date" data-provide="datepicker" data-date-format="dd/mm/yyyy"
                  class="form-control" id="date-booking-start" placeholder="From">
                </div>
              </div>
              <div class="col-xs-12 col-sm-6">
                <div class="form-group">
                  <input type="date" data-provide="datepicker" data-date-format="dd/mm/yyyy" class="form-control" id="date-booking-end" placeholder="Until">
                </div>
              </div>
            </div> -->
            <div>
              <!-- <button type="book" class="btn btn-danger form-group form-control">Send Booking Request</button> -->
              <%= link_to "Book this stud!", new_user_stallion_booking_path(@stallion.user_id, @stallion.id), class: "navbar-wagon-item navbar-wagon-button btn" %>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Stallion details-->
<div class="wrapper-gray">
  <div class="container">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1 col-sm-7 col-sm-offset-1">
        <div id="stallion-full-details">

          <h5 class="padded-bottom">About this listing</h5>
          <p><%= @stallion.description %></p>
          <div>
            <p><%= link_to "Contact Owner", "#", class: "link-red" %></p>
          </div>

          <div class="row">
            <div class="details-section">
              <div class="col-xs-12 col-sm-4">
                <div class="details-section-header">
                  Stallion info
                </div>
              </div>
              <div class="col-xs-12 col-sm-8">
                <ul class= "list-no-left-padding list-no-bullets">
                  <!-- need to keep unless clause in until we make date of birth mandatory
                  in stallion creation -->
                  <% unless @stallion.date_of_birth.nil? %>
                  <li>Date of Birth: <strong><%= @stallion.date_of_birth.strftime('%d/%m/%Y') %></strong></li>
                  <% end %>
                  <li>Category: <strong><%= @stallion.category %></strong></li>
                  <li>Breed: <strong><%= @stallion.breed %></strong></li>
                </ul>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="details-section">

              <div class="col-xs-12 col-sm-4">
                <div class="details-section-header">
                  Services
                </div>
              </div>

              <div class="col-xs-12 col-sm-8">
                <ul class= "list-inline list-no-left-padding list-no-bullets">
                <!--This next bit goes through all the available services and
                adds an entry if the value is true (i.e. the service is
                available) -->
                  <% Stallion::SERVICES.each do |service| %>
                    <!-- I'm using the send method because just passing .service
                    didn't seem to work. Send is just an alternative way of passing
                    a method. Tis in the Ruby documentation for Object -->
                    <% if @stallion.send "#{service.to_sym}"%>
                      <li class="li-halfwidth">
                        <%= image_tag "#{service}.svg", class: "service-icon", width: 25, height: 25 %> <%= service.humanize%>
                      </li>
                    <% end %>
                  <% end %>
                </ul>
              </div>

            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<div class="wrapper-white">
  <div class="container">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1 col-sm-7 col-sm-offset-1">
        REVIEWS GO HERE
      </div>
    </div>
  </div>
</div>


<div>
<%= link_to edit_user_stallion_path do %>
  <button class="btn btn-primary" type="button">Edit Stallion</button>
<% end %>

<p><%= link_to "Delete", user_stallion_path(@stallion.user, @stallion.id), {class: "btn btn-primary", :method => :delete} %></p>
</div>