config/routes.rb
Rails.application.routes.draw do


  root 'pages#home'
  # get 'users/show'

  get '/filter', to: 'pages#filter'

  devise_for :users, :path => 'accounts'

  resources :users, only: [:show] do
    resources :stallions do
      resources :bookings, only: [:new, :create]
    end

    # resources :profiles, only: [:new, :create, :edit, :update]
  end

  get 'users/:id/profile' => 'profiles#show', as: :user_profile
  get 'users/:id/profile/new' => 'profiles#new', as: :new_user_profile
  post 'users/profiles' => 'profiles#create'
  get 'users/:id/profile/edit' => 'profiles#edit', as: :edit_user_profile
  patch 'users/:id/profile' => 'profiles#update'

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :email, presence: true
  validates :first_name, presence: true
  has_many :bookings
  has_many :stallions
  has_one :profile

  after_create :create_profile
  # has_many :stallions, through: :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  private

  def create_profile
    self.profile = Profile.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
    set_user()
  end



    private

  def set_user
    @user = User.find(current_user.id)
    User.find(current_user.id).stallion_owner = true
  end

  # image is from seed, photo is from cloudinary
  def user_params
    params.require(:user).permit(
    :email,
    :encrypted_password,
    :reset_password_token,
    :reset_password_sent_at,
    :remember_created_at,
    :sign_in_count,
    :current_sign_in_at,
    :last_sign_in_at,
    :current_sign_in_ip,
    :last_sign_in_ip,
    :created_at,
    :updated_at,
    :first_name,
    :last_name,
    :city,
    :postal_code,
    :average_rating,
    :stallion_owner)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container">
  <h1>Hello <%= @user.first_name %></h1>
  <p><%= @user.email %></p>


 <!-- Button (call-to-action) -->
<%= link_to "Add Stallion", new_user_stallion_path(@user.id), class: "navbar-wagon-item navbar-wagon-button btn" %>
</div>





<div class="container">
  <div class="row add-margin-top">

    <h1> My Stallions </h1>
    <% @user.stallions.all.each do |stallion| %>
    <div class="col-xs-12 col-sm-3">

      <%= link_to user_stallion_path(stallion.user, stallion) do %>
      <div class="card" style="background-image: url('<%= image_url stallion.photo %>'), linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">

        <div class="card-category"><%= stallion.town %></div>
        <div class="card-description">
          <h2><%= stallion.name %></h2>
          <p><%= stallion.category %>  -  <%= stallion.breed %></p>
        </div>
<!--         <a href="#" class="card-link"></a> -->
      </div>

       <%end %>
    </div>
    <% end %>
  </div>
</div>





<div class="container">
  <div class="row add-margin-top">

  <h1> My Bookings </h1>
    <% @user.bookings.all.each do |booking| %>
    <div class="col-xs-12 col-sm-3">
      <h3><%= booking.date %></h3>
      <%= link_to user_stallion_path(booking.stallion_owner_id, booking.stallion_id) do %>
      <div class="card" style="background-image: url('<%= image_url Stallion.find(booking.stallion_id).photo %>'), linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">

        <div class="card-category">Popular</div>
        <div class="card-description">
          <h2><%= Stallion.find(booking.stallion_id).name %></h2>
          <p><%= Stallion.find(booking.stallion_id).category %>  -  <%= Stallion.find(booking.stallion_id).breed %></p>
        </div>
<!--         <a href="#" class="card-link"></a> -->
      </div>

       <%end %>
    </div>
    <% end %>
  </div>
</div>