config/routes.rb
Rails.application.routes.draw do


  root 'pages#home'
  # get 'users/show'

  get '/filter', to: 'pages#filter'

  devise_for :users, :path => 'accounts'

  resources :users, only: [:show] do
    resources :stallions do
      resources :bookings, only: [:new, :create]
    end

    # resources :profiles, only: [:new, :create, :edit, :update]
  end

  get 'users/:id/profile' => 'profiles#show', as: :user_profile
  get 'users/:id/profile/new' => 'profiles#new', as: :new_user_profile
  post 'users/profiles' => 'profiles#create'
  get 'users/:id/profile/edit' => 'profiles#edit', as: :edit_user_profile
  patch 'users/:id/profile' => 'profiles#update'

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

<i class="fa fa-facebook fa-2x"></i>
<i class="fa fa-twitter fa-2x"></i>
<i class="fa fa-linkedin fa-2x"></i>
<i class="fa fa-rss fa-2x"></i>
<i class="fa fa-youtube fa-2x"></i>
<i class="fa fa-google-plus fa-2x"></i>




</div>

app/views/shared/_form_add_booking.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">

      <h1><%= @form_variables[:header] %> Booking</h1>

      <%= simple_form_for [@user, @stallion, @booking] do |f| %>
      <%= f.input :date, as: :date, start_year: Date.today.year,
      end_year: Date.today.year + 2,
      order: [:day, :month, :year]%>
      <%= f.submit value: "Book this stud!", class: "btn btn-primary form-control"%>
      <% end %>
    </div>
  </div>
</div>




            <!-- <input type="date" data-provide="datepicker" data-date-format="dd/mm/yyyy"
            class="form-control" id="date-booking-start" placeholder="date"> -->
          </div>
        </div>

      </div>
      <div>
        <!-- <button type="book" class="btn btn-danger form-group form-control">Send Booking Request</button> -->

      </div>
    </form>
  </div>
</div>

app/views/shared/_form_add_edit_stallion.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">

      <h1><%= @form_variables[:header] %> Stallion</h1>

      <%= simple_form_for [@user, @stallion] do |f| %>
      <%= f.input :name %>
      <%= f.input :date_of_birth, as: :date, start_year: Date.today.year - 30,
      end_year: Date.today.year,
      order: [:day, :month, :year]%>
      <%= f.input :town, placeholder: "Brussels" %>
      <%= f.input :country, as: :string %>
      <!-- We should add a table for categories at some point. -->
      <%= f.input :category, collection: Stallion::CATEGORIES %>
      <%= f.input :breed, collection: Stallion::BREEDS %>
      <%= f.input :colour %>
      <%= f.input :lineage %>
      <%= f.input :description %>
      <ul class="list-inline list-no-left-padding list-no-bullets">
        <li><%= f.input :sperm_only, as: :boolean, checked_value: true, unchecked_value: false %></li>
        <li><%= f.input :stabling, as: :boolean, checked_value: true, unchecked_value: false %></li>
        <li><%= f.input :owner_bed, as: :boolean, checked_value: true, unchecked_value: false %></li>
        <li><%= f.input :shooting, as: :boolean, checked_value: true, unchecked_value: false %></li>
        <li><%= f.input :malt_whisky, as: :boolean, checked_value: true, unchecked_value: false %></li>
      </ul>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit class: "btn btn-primary form-control"%>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_form_edit_profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <h1><%= @profile.profile_made ? "Edit Profile" : "Create Profile" %></h1>

      <%= simple_form_for [@user, @profile] do |f| %>
      <%= f.input :last_name %>
      <%= f.input :title, collection: (Profile::TITLES).sort %>
      <%= f.input :net_worth, label: "Net worth ($ Millions)" %>
      <%= f.input :estate %>
      <%= f.input :town %>
      <%= f.input :country, as: :string  %>
      <%= f.input :stallion_owner, as: :boolean, checked_value: true, unchecked_value: false %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>

      <%= f.submit class: "btn btn-primary form-control"%>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->

      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <!-- <i class="fa fa-envelope-o"></i> -->
          <!-- <div class="badge badge-blue">3</div> -->
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "#{current_user.profile.photo}", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
                <%= link_to user_profile_path(current_user.id) do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Different buttons depending on login status and stallion_owner status -->
    <!-- My Bookings only appears if user is logged in -->

    <!-- Button for registering as SO changes to my stable if user is a horse owner -->
    <% button_text = current_user && !current_user.stallions.empty? ? "My Stable" : "Pimp Your Horse" %>

    <%= link_to "#{button_text}", if current_user
                                    user_path(current_user.id)
                                    else new_user_session_path
                                 end,
        class: "navbar-wagon-item navbar-wagon-button btn" %>


  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>