config/routes.rb
Rails.application.routes.draw do


  root 'pages#home'
  # get 'users/show'

  get '/filter', to: 'pages#filter'

  devise_for :users, :path => 'accounts'

  resources :users, only: [:show] do
    resources :stallions do
      resources :bookings, only: [:new, :create]
    end

    # resources :profiles, only: [:new, :create, :edit, :update]
  end

  get 'users/:id/profile' => 'profiles#show', as: :user_profile
  get 'users/:id/profile/new' => 'profiles#new', as: :new_user_profile
  post 'users/profiles' => 'profiles#create'
  get 'users/:id/profile/edit' => 'profiles#edit', as: :edit_user_profile
  patch 'users/:id/profile' => 'profiles#update'

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/pages/filter.html.erb
<div class="wrapper-white">
  <div class="container">
    <div class="filter-details-section">
      <div class="row">
        <div class="col-xs-6 col-sm-6">
          <%= simple_form_for :search, url: filter_path, method: :get do |f| %>
          <%= f.input :category, label: 'Pick a category to filter', collection: Stallion.categories  %>
          <%= f.input :breed, collection: Stallion.breeds, label: 'And/or try filtering on a particular breed', as: :radio_buttons   %>
          <%= f.input :country, collection: Stallion.countries, label: 'And/or try filtering on a particular country location'   %>
          <%= f.input :average_rating,  collection: Stallion.ratings, label: 'And/or try filtering on the particular average rating' %>
          <%= f.button :submit, "Filter those Sires, bitch!", class: "btn btn-lg btn-info" %>
          <% end %>
        </div>
        <div class="col-xs-6 col-sm-6">
          <% @stallions.each do |stallion| %>
            <%=  link_to user_stallion_path(stallion.user, stallion) do %>
              <div class="card" style="background-image: url('<%= image_url stallion.photo %>'), linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">
                <div class="card-category">Popular</div>
                <div class="card-description">
                  <h2><%= stallion.name %></h2>
                  <p><%= stallion.category %>  -  <%= stallion.breed %></p>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <!--         <a href="#" class="card-link"></a> -->
    </div>

  </div>
</div>
</div>




<div class="wrapper-white">
  <div class="container">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1 col-sm-7 col-sm-offset-1">

      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!doctype html>
<html>
<head>
  <meta  charset="UTF-8">

  <title>MareBnB</title>

  <style>

  .video {
    position:absolute;
    width:100%;
    max-height:100%;
    z-index: -1;
    margin-bottom: 20px;
  }


  .center {
    display: flex;
    justify-content: center;
    align-items: center;
    color: white;
    height: 100vh;
    background-size: cover;
    text-align: center;
  }


  .badge-bordered {
    box-shadow: 0 1px 2px rgba(0,0,0,0.2);
    border: white 2px solid;
    color: white;
    padding: 8px;
  }

  </style>

</head>

<body>

  <div>
    <%= video_tag("Rolling-horse.mp4", :autoplay => true, class: "video") %>

    <div class="center"><lb>
     <%= image_tag("logo.png", size: "300x300") %>
        <lb>
        <h3>SOWING OATS SINCE 2016</h3><lb>
        <h4><%= link_to "See our studs!", filter_path, class: "badge-bordered" %></h4>

  </div>

<br>


  <div class="container add-margin-top">
    <div class="row">
      <% Stallion.all.each do |stallion| %>
      <div class="col-xs-12 col-sm-3">
    <%=  link_to user_stallion_path(stallion.user, stallion) do %>
        <div class="card" style="background-image: url('<%= image_url stallion.photo %>'), linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">

          <div class="card-category">Popular</div>
          <div class="card-description">
            <h2><%= stallion.name %></h2>
            <p><%= stallion.category %>  -  <%= stallion.breed %></p>
          </div>
  <!--         <a href="#" class="card-link"></a> -->
        </div>

        <% end %>
      </div>
      <% end %>
    </div>
  </div>

</body>